[env:stepper_controller]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
framework = arduino

; Library dependencies
lib_deps = 
    teemuatlut/TMCStepper@^0.7.3
    fastled/FastLED@^3.10.3
    bblanchon/ArduinoJson@^7.0.0
