[env:hand_scanner]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino

; OTA partition scheme for 4MB flash
board_build.partitions = min_spiffs.csv

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1

; Serial monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_port = COM101

; Library dependencies
lib_deps = 
    adafruit/Adafruit NeoPixel@^1.12.3
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    bblanchon/ArduinoJson@^7.1.0

; Upload settings
upload_speed = 921600
upload_port = COM101

; Debug settings
debug_tool = esp-prog
debug_init_break = tbreak setup
